"""init

Revision ID: 31a359c21cae
Revises: 
Create Date: 2026-07-16 12:47:51.895089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a359c21cae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('phonetic', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('pos', sa.Text(), nullable=True),
    sa.Column('collins', sa.Integer(), nullable=True),
    sa.Column('oxford', sa.Integer(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('bnc', sa.Integer(), nullable=True),
    sa.Column('frq', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    op.create_table('book_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_words_book_order', 'book_words', ['book_id', 'order_index'], unique=False)
    op.create_index('ix_book_words_book_word', 'book_words', ['book_id', 'word_id'], unique=True)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('order_json', sa.Text(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rounds_book_status', 'rounds', ['book_id', 'status'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('learn_completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_round_status', 'sessions', ['round_id', 'status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('order_json', sa.Text(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_session', 'reviews', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_session', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_sessions_round_status', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('user_profile')
    op.drop_index('ix_rounds_book_status', table_name='rounds')
    op.drop_table('rounds')
    op.drop_index('ix_book_words_book_word', table_name='book_words')
    op.drop_index('ix_book_words_book_order', table_name='book_words')
    op.drop_table('book_words')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_table('words')
    op.drop_table('books')
    # ### end Alembic commands ###
